package itq.test.service;

import com.fasterxml.jackson.databind.ObjectMapper;
import itq.test.entities.Document;
import itq.test.service.dto.DocumentCreateRequest;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.context.ApplicationContext;
import org.springframework.stereotype.Component;

import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.util.Random;

@Component
public class DocumentGenerator implements CommandLineRunner {

    @Value("${generator.numFiles:10}")
    private int numFiles;

    private static final HttpClient client = HttpClient.newHttpClient();
    private final Logger log = LoggerFactory.getLogger(DocumentGenerator.class);

    private final ApplicationContext context;

    public DocumentGenerator(ApplicationContext context) {
        this.context = context;
    }

    @Override
    public void run(String... args) {
        final Random random = new Random();
        for (int i = 0; i < numFiles; i++) {
            var data = new DocumentCreateRequest();
            data.setAuthor("autogen@author.mail.com");
            data.setTitle(String.format("%s%d", "autoGeneratedAuthor", random.nextInt(10, 1000)));
            ObjectMapper objectMapper = new ObjectMapper();
            try {
                String jsonPayload = objectMapper.writeValueAsString(data);
                HttpRequest request = HttpRequest.newBuilder()
                        .uri(URI.create("http://127.0.0.1:8080/api/v1/document/create"))
                        .header("Content-Type", "application/json")
                        .POST(HttpRequest.BodyPublishers.ofString(jsonPayload))
                        .build();
                client.send(request, HttpResponse.BodyHandlers.ofString());
            } catch (Exception e) {
                log.error("Exception", e);
            }
        }
        int exitCode = SpringApplication.exit(context, () -> 0);
        System.exit(exitCode);
    }
}
